/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartRouteImport } from './routes/start'
import { Route as LiveRouteImport } from './routes/live'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatPeerRouteImport } from './routes/chat.$peer'
import { Route as ApiPublicSheetsLogRouteImport } from './routes/api/public/sheets-log'

const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPeerRoute = ChatPeerRouteImport.update({
  id: '/chat/$peer',
  path: '/chat/$peer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSheetsLogRoute = ApiPublicSheetsLogRouteImport.update({
  id: '/api/public/sheets-log',
  path: '/api/public/sheets-log',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/start': typeof StartRoute
  '/chat/$peer': typeof ChatPeerRoute
  '/api/public/sheets-log': typeof ApiPublicSheetsLogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/start': typeof StartRoute
  '/chat/$peer': typeof ChatPeerRoute
  '/api/public/sheets-log': typeof ApiPublicSheetsLogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/start': typeof StartRoute
  '/chat/$peer': typeof ChatPeerRoute
  '/api/public/sheets-log': typeof ApiPublicSheetsLogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/live' | '/start' | '/chat/$peer' | '/api/public/sheets-log'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/live' | '/start' | '/chat/$peer' | '/api/public/sheets-log'
  id:
    | '__root__'
    | '/'
    | '/live'
    | '/start'
    | '/chat/$peer'
    | '/api/public/sheets-log'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveRoute: typeof LiveRoute
  StartRoute: typeof StartRoute
  ChatPeerRoute: typeof ChatPeerRoute
  ApiPublicSheetsLogRoute: typeof ApiPublicSheetsLogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$peer': {
      id: '/chat/$peer'
      path: '/chat/$peer'
      fullPath: '/chat/$peer'
      preLoaderRoute: typeof ChatPeerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sheets-log': {
      id: '/api/public/sheets-log'
      path: '/api/public/sheets-log'
      fullPath: '/api/public/sheets-log'
      preLoaderRoute: typeof ApiPublicSheetsLogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveRoute: LiveRoute,
  StartRoute: StartRoute,
  ChatPeerRoute: ChatPeerRoute,
  ApiPublicSheetsLogRoute: ApiPublicSheetsLogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
